FROM python:3.7-slim
FROM jjanzic/docker-python3-opencv

ENV PYTHONIOENCODING=utf-8
COPY . /app
WORKDIR /app
RUN apt update && apt install -y libsm6 libxext6
RUN apt-get -y install tesseract-ocr
RUN pip install --upgrade pip
RUN pip install -r requirements.txt 
EXPOSE 5000
ENTRYPOINT ["flask"]
CMD ["run", "--host=0.0.0.0"]
